import type { AdAccount, Campaign, Creative } from "@/types/ads";
import { buildDaily, type PerformanceProfile } from "./series";

export const DEMO_ACCOUNT: AdAccount = {
  id: "act_demo_1042",
  name: "Fluentway English Academy",
  currency: "IDR",
  timeZone: "Asia/Makassar",
  providerLabel: "Demo Ads Provider",
  mode: "demo",
};

interface AdSeed {
  id: string;
  name: string;
  status: "active" | "paused";
  creative: Creative;
  profile: PerformanceProfile;
}

function ad(campaignId: string, adSetId: string, seed: AdSeed) {
  return {
    id: seed.id,
    adSetId,
    campaignId,
    name: seed.name,
    status: seed.status,
    creative: seed.creative,
    daily: buildDaily(seed.id, seed.profile),
  };
}

const PLACEMENTS = ["Feed", "Stories", "Reels", "Search partners"];

export const DEMO_CAMPAIGNS: Campaign[] = [
  {
    id: "cmp_course_purchase",
    accountId: DEMO_ACCOUNT.id,
    name: "English Course - Purchase Push",
    status: "active",
    objective: "conversions",
    budget: { amount: 15_000_000, period: "lifetime" },
    startDate: "2026-08-02",
    endDate: "2026-09-15",
    adSets: [
      {
        id: "adset_professionals",
        campaignId: "cmp_course_purchase",
        name: "Working Professionals 25-34",
        status: "active",
        budget: { amount: 180_000, period: "daily" },
        audience: {
          name: "Career upskillers",
          sizeEstimate: 1_850_000,
          locations: ["Jakarta", "Bandung", "Surabaya"],
          ageRange: "25-34",
          interests: ["Career development", "Business English", "Online courses"],
        },
        placements: PLACEMENTS.slice(0, 3),
        optimizationGoal: "Purchases",
        bidStrategy: "Lowest cost",
        ads: [
          ad("cmp_course_purchase", "adset_professionals", {
            id: "ad_pro_testimonial",
            name: "Testimonial - Promotion in 6 months",
            status: "active",
            creative: {
              id: "cr_pro_testimonial",
              name: "Testimonial video 30s",
              format: "video",
              headline: "From hesitant to leading client calls",
              body: "Structured evening classes built for full-time workers. Live practice twice a week.",
              callToAction: "Enroll now",
              accent: "blue",
            },
            profile: {
              dailySpend: 85_000,
              cpm: 34_000,
              ctr: 0.019,
              cvr: 0.0085,
              aov: 620_000,
              reachRatio: 0.63,
              drift: 0.004,
            },
          }),
          ad("cmp_course_purchase", "adset_professionals", {
            id: "ad_pro_offer",
            name: "Offer - Early bird bundle",
            status: "active",
            creative: {
              id: "cr_pro_offer",
              name: "Static offer card",
              format: "image",
              headline: "Early bird: 2 months of live classes",
              body: "Lock the intake price before the September cohort closes.",
              callToAction: "Get the bundle",
              accent: "violet",
            },
            profile: {
              dailySpend: 70_000,
              cpm: 31_500,
              ctr: 0.016,
              cvr: 0.0074,
              aov: 585_000,
              reachRatio: 0.66,
              drift: -0.002,
            },
          }),
        ],
      },
      {
        id: "adset_students",
        campaignId: "cmp_course_purchase",
        name: "University Students 18-24",
        status: "active",
        budget: { amount: 120_000, period: "daily" },
        audience: {
          name: "Campus learners",
          sizeEstimate: 2_400_000,
          locations: ["Yogyakarta", "Malang", "Depok"],
          ageRange: "18-24",
          interests: ["IELTS", "Study abroad", "Student discounts"],
        },
        placements: PLACEMENTS,
        optimizationGoal: "Purchases",
        bidStrategy: "Lowest cost",
        ads: [
          ad("cmp_course_purchase", "adset_students", {
            id: "ad_student_scholarship",
            name: "Scholarship angle - Study abroad",
            status: "active",
            creative: {
              id: "cr_student_scholarship",
              name: "Carousel - scholarship path",
              format: "carousel",
              headline: "Reach IELTS 7.0 with a study plan",
              body: "Weekly mock tests and speaking clinics with certified tutors.",
              callToAction: "See the plan",
              accent: "amber",
            },
            profile: {
              dailySpend: 60_000,
              cpm: 44_500,
              ctr: 0.011,
              cvr: 0.0065,
              aov: 410_000,
              reachRatio: 0.58,
              drift: -0.012,
            },
          }),
          ad("cmp_course_purchase", "adset_students", {
            id: "ad_student_discount",
            name: "Student discount - Reels cut",
            status: "active",
            creative: {
              id: "cr_student_discount",
              name: "Reels 15s vertical",
              format: "video",
              headline: "Student price, same live classes",
              body: "Show a valid student card and join the evening cohort.",
              callToAction: "Claim discount",
              accent: "rose",
            },
            profile: {
              dailySpend: 45_000,
              cpm: 39_000,
              ctr: 0.013,
              cvr: 0.0043,
              aov: 395_000,
              reachRatio: 0.61,
              drift: -0.016,
            },
          }),
        ],
      },
      {
        id: "adset_lookalike",
        campaignId: "cmp_course_purchase",
        name: "Lookalike - Past Buyers 3%",
        status: "active",
        budget: { amount: 190_000, period: "daily" },
        audience: {
          name: "Lookalike of 2025 buyers",
          sizeEstimate: 920_000,
          locations: ["Indonesia"],
          ageRange: "22-40",
          interests: ["Language learning", "Professional certification"],
        },
        placements: PLACEMENTS.slice(0, 2),
        optimizationGoal: "Purchases",
        bidStrategy: "Cost cap",
        ads: [
          ad("cmp_course_purchase", "adset_lookalike", {
            id: "ad_lookalike_proof",
            name: "Proof - 1,200 graduates",
            status: "active",
            creative: {
              id: "cr_lookalike_proof",
              name: "Social proof static",
              format: "image",
              headline: "1,200 graduates, one syllabus",
              body: "Placement test, level match, then eight weeks of live speaking practice.",
              callToAction: "Start today",
              accent: "emerald",
            },
            profile: {
              dailySpend: 160_000,
              cpm: 29_000,
              ctr: 0.023,
              cvr: 0.0084,
              aov: 620_000,
              reachRatio: 0.68,
              drift: 0.004,
            },
          }),
        ],
      },
    ],
  },
  {
    id: "cmp_retargeting",
    accountId: DEMO_ACCOUNT.id,
    name: "Retargeting - Pricing Page Visitors",
    status: "active",
    objective: "conversions",
    budget: { amount: 4_200_000, period: "lifetime" },
    startDate: "2026-08-09",
    endDate: "2026-09-15",
    adSets: [
      {
        id: "adset_visitors_30d",
        campaignId: "cmp_retargeting",
        name: "Site Visitors 30D",
        status: "active",
        budget: { amount: 130_000, period: "daily" },
        audience: {
          name: "Pricing page, no purchase",
          sizeEstimate: 42_000,
          locations: ["Indonesia"],
          ageRange: "18-45",
          interests: ["Visited pricing page"],
        },
        placements: PLACEMENTS.slice(0, 2),
        optimizationGoal: "Purchases",
        bidStrategy: "Lowest cost",
        ads: [
          ad("cmp_retargeting", "adset_visitors_30d", {
            id: "ad_retarget_reminder",
            name: "Reminder - Seats left",
            status: "active",
            creative: {
              id: "cr_retarget_reminder",
              name: "Urgency static",
              format: "image",
              headline: "Your seat is still open",
              body: "The September cohort starts in two weeks. Finish your enrollment.",
              callToAction: "Finish enrollment",
              accent: "blue",
            },
            profile: {
              dailySpend: 70_000,
              cpm: 26_500,
              ctr: 0.031,
              cvr: 0.0055,
              aov: 640_000,
              reachRatio: 0.42,
              drift: -0.004,
            },
          }),
          ad("cmp_retargeting", "adset_visitors_30d", {
            id: "ad_retarget_faq",
            name: "FAQ - Payment options",
            status: "paused",
            creative: {
              id: "cr_retarget_faq",
              name: "FAQ carousel",
              format: "carousel",
              headline: "Pay in three installments",
              body: "No card needed. Bank transfer and e-wallet supported.",
              callToAction: "See options",
              accent: "violet",
            },
            profile: {
              dailySpend: 30_000,
              cpm: 28_000,
              ctr: 0.024,
              cvr: 0.0049,
              aov: 600_000,
              reachRatio: 0.45,
              drift: -0.002,
            },
          }),
        ],
      },
    ],
  },
  {
    id: "cmp_awareness",
    accountId: DEMO_ACCOUNT.id,
    name: "Cohort Launch - Reach",
    status: "paused",
    objective: "awareness",
    budget: { amount: 2_000_000, period: "lifetime" },
    startDate: "2026-07-20",
    endDate: "2026-08-20",
    adSets: [
      {
        id: "adset_broad_interest",
        campaignId: "cmp_awareness",
        name: "Broad Interest - Language Learning",
        status: "active",
        budget: { amount: 80_000, period: "daily" },
        audience: {
          name: "Broad language learners",
          sizeEstimate: 6_100_000,
          locations: ["Indonesia"],
          ageRange: "18-50",
          interests: ["Language learning"],
        },
        placements: PLACEMENTS,
        optimizationGoal: "Reach",
        bidStrategy: "Lowest cost",
        ads: [
          ad("cmp_awareness", "adset_broad_interest", {
            id: "ad_awareness_teaser",
            name: "Teaser - Cohort opening",
            status: "active",
            creative: {
              id: "cr_awareness_teaser",
              name: "Brand teaser 10s",
              format: "video",
              headline: "Speak with confidence this year",
              body: "Live classes, small groups, certified tutors.",
              callToAction: "Learn more",
              accent: "amber",
            },
            profile: {
              dailySpend: 50_000,
              cpm: 12_500,
              ctr: 0.008,
              cvr: 0.0009,
              aov: 520_000,
              reachRatio: 0.74,
              drift: -0.006,
            },
          }),
        ],
      },
    ],
  },
];
